channels:
  - nvidia
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - cuda=12.1.0
  - numpy=1.26.4
  - pillow=10.3.0
  - pip=24.0.0
  - plyfile=1.0.3
  - python=3.12.2
  - pytorch=2.3.0
  - pytorch-cuda=12.1
  - setuptools=69.5.1
  - torchvision=0.18.0
  - tqdm=4.66.2
  - wheel=0.43.0
