name: gaussian_splatting
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - cuda=12.1.0
  - numpy=1.26.4
  - pillow=10.2.0
  - pip=24.0.0
  - plyfile=1.0.3
  - python=3.12.2
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - setuptools=69.2.0
  - torchaudio=2.2.2
  - torchvision=0.17.2
  - tqdm=4.66.2
  - wheel=0.41.2
